//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IaniDProject.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Web_sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web_sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IaniDProject.App_GlobalResources.Web.sitemap", typeof(Web_sitemap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Количка.
        /// </summary>
        internal static string CartPage_title {
            get {
                return ResourceManager.GetString("CartPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Контакти.
        /// </summary>
        internal static string ContactsPage_title {
            get {
                return ResourceManager.GetString("ContactsPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Категории.
        /// </summary>
        internal static string DetailsCategoryPage_title {
            get {
                return ResourceManager.GetString("DetailsCategoryPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Детайли.
        /// </summary>
        internal static string DetailsProductPage_title {
            get {
                return ResourceManager.GetString("DetailsProductPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  За нас.
        /// </summary>
        internal static string For_usPage_title {
            get {
                return ResourceManager.GetString("For_usPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Начало.
        /// </summary>
        internal static string HomePage_title {
            get {
                return ResourceManager.GetString("HomePage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Услуги.
        /// </summary>
        internal static string ServicesPage_title {
            get {
                return ResourceManager.GetString("ServicesPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Карта на сайта.
        /// </summary>
        internal static string SiteMapPage_title {
            get {
                return ResourceManager.GetString("SiteMapPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  История на поръчката.
        /// </summary>
        internal static string UserHistoryPage_title {
            get {
                return ResourceManager.GetString("UserHistoryPage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моят профил.
        /// </summary>
        internal static string UserProfilPage_title {
            get {
                return ResourceManager.GetString("UserProfilPage.title", resourceCulture);
            }
        }
    }
}
